---
- hosts: ansible
  tasks:
  - name: creating image from Dockerfile
    command: docker build -t regapp:latest .

    args:
      chdir: /opt/docker



  - name: creating reserve space in D HUB
    command: docker tag regapp:latest dakshayk/regapp:latest     
    # command: docker tag regapp:latest(image name in base machine)  dakshayk/regapp:latest (dockerhub username/reservespace name)

    
  - name: pushing image to D HUB
    command: docker push dakshayk/regapp:latest #(pushing image(regapp:latest) to the reserve space 
