---
- hosts: dockerhost
  tasks:
    - name: stop container
      command: docker stop regapp-server
      ignore_errors: yes

    - name: delete container
      command: docker rm regapp-server
      ignore_errors: yes


    - name: deleting image
      command: docker rmi dakshayk/regapp
      ignore_errors: yes

    - name: create container
      command: docker run -dt --name regapp-server -p 8082:8080 dakshayk/regapp
